#ifndef _MULTIBOOT_H_
#define _MULTIBOOT_H_

#define MULTIBOOT_HEADER_MAGIC		0x1BADB002
#define MULTIBOOT_HEADER_FLAGS		0x00010003
#define MULTIBOOT_BOOTLOADER_MAGIC	0x2BADB002

#ifndef MULTIBOOT_ASM


#endif

#endif
