#Makefile for SGOS2:services


all:
	make -Capi
	make -Clibc
	make -Cmsg
	make -Csystem
	make -Cspeaker
	make -Chello

clean:
	make -Capi clean
	make -Clibc clean
	make -Cmsg clean
	make -Csystem clean
	make -Cspeaker clean
	make -Chello clean

