#Makefile for SGOS2:services


all:
	make -C../crt
	make -C../api
	make -Cfs
	make -Chd
	make -Cservicemanager
	make -Chello
	make -Cwprocess
	make -Cstartup
	make -Cspeaker
	make -Cacpi
	make -Ckeyboard
	make -Cvesa
	make -Ctime
	make -Cwkernel
	make -Cwadvapi
	make -Cmsys
clean:
	make -C../crt clean
	make -C../api clean
	make -Cfs clean
	make -Chd clean
	make -Cservicemanager clean
	make -Chello clean
	make -Cwprocess clean
	make -Cstartup clean
	make -Cspeaker clean
	make -Cacpi clean
	make -Ckeyboard clean
	make -Cvesa clean
	make -Ctime clean
	make -Cwkernel clean
	make -Cwadvapi clean
	make -Cmsys clean

